/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version("6.1.0")
    id("org.checkerframework") version("0.5.17")
    java
}


repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()

    flatDir {
        dirs = setOf(file("../lib"))
    }
}

dependencies {
    implementation("com.google.guava:guava:29.0-jre")
    implementation("com.diozero:diozero-core:1.1.7")
    implementation("com.diozero:diozero-provider-pigpio:1.1.7")
    implementation("org.java-websocket:Java-WebSocket:1.5.1")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation(fileTree("../lib"))
//    implementation("org.slf4j:slf4j-api:jar:1.7.2")
//    implementation("uk.co.caprica:vlcj:jar:2.4.1")
//    implementation("net.java.dev.jna:jna:jar:4.1.0")
}

application {
    // Define the main class for the application.
    mainClass.set("ribitcore.App")
    mainClassName = "ribitcore.App"
}

java {
    sourceCompatibility = JavaVersion.VERSION_15
    targetCompatibility = JavaVersion.VERSION_15
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "ribitcore.App"
    }
}

tasks {
    named<ShadowJar>("shadowJar") {
        archiveBaseName.set("shadow")
        mergeServiceFiles()
        manifest {

            attributes(mapOf("Main-Class" to "ribitcore.App"))
        }
    }
}

tasks {
    build {
        dependsOn(shadowJar)
    }
}