/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    id("org.checkerframework") version("0.5.17")
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    implementation("com.google.guava:guava:29.0-jre")
    implementation("com.diozero:diozero-core:1.1.6")

    compileOnly("org.checkerframework:checker-qual:3.4.0")
    checkerFramework("org.checkerframework:checker:3.4.0")
}

application {
    // Define the main class for the application.
    mainClass.set("ribitcore.App")
}

java {
    sourceCompatibility = JavaVersion.VERSION_15
    targetCompatibility = JavaVersion.VERSION_15
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "ribitcore.App"
    }
}
