/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ribitcore;

public class App {

    public static void main(String[] args) {

        new RibitBootstrapper().start();

    }
}