/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ribitcore;

import com.diozero.api.Servo;
import com.diozero.util.SleepUtil;
import org.tinylog.Logger;

public class App {

    public static void main(String[] args) {

        new RibitBootstrapper().start();

    }
}